name: Kex test CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Run Kex tests docker
      uses: vorpal-research/kex-dockerfile@v4
